set (TEST_WORKSPACE "test_workspace")

if (NOT EXISTS ${CMAKE_BINARY_DIR}/${TEST_WORKSPACE})
  file (MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/${TEST_WORKSPACE})
endif ()

get_filename_component (TEST_PROGRAM_NAME ${TEST_PROGRAM} NAME)

set (TEST_OUTPUT_FILE
  ${CMAKE_BINARY_DIR}/${TEST_WORKSPACE}/${TEST_PROGRAM_NAME}.out)

set (TEST_ERROR_FILE
  ${CMAKE_BINARY_DIR}/${TEST_WORKSPACE}/${TEST_PROGRAM_NAME}.err)

execute_process (
  COMMAND ${TEST_PROGRAM}
  OUTPUT_FILE ${TEST_OUTPUT_FILE}
  ERROR_FILE ${TEST_ERROR_FILE}
  RESULT_VARIABLE TEST_RESULT
  OUTPUT_VARIABLE TEST_ERROR
  ERROR_VARIABLE TEST_ERROR)

message (STATUS "${TEST_RESULT}")
message (STATUS "${TEST_ERROR}")

if (${TEST_RESULT} STREQUAL "Child aborted")
  message (FATAL_ERROR "FAILURE: ${TEST_PROGRAM_NAME}")
endif ()
